name = "Tes" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
routes = [
  { pattern = "id.jeans.eu.org", custom_domain = true },
  { pattern = "ava.game.naver.com.id.jeans.eu.org", custom_domain = true },
  { pattern = "graph.instagram.com.id.jeans.eu.org", custom_domain = true },
  { pattern = "quiz.int.vidio.com.id.jeans.eu.org", custom_domain = true },
  { pattern = "investors.spotify.com.id.jeans.eu.org", custom_domain = true },
  { pattern = "zaintest.vuclip.com.id.jeans.eu.org", custom_domain = true },
  { pattern = "cache.netflix.com.id.jeans.eu.org", custom_domain = true },
  { pattern = "blog.webex.com.id.jeans.eu.org", custom_domain = true },
  { pattern = "support.zoom.us.id.jeans.eu.org", custom_domain = true },
]

[vars]
# UUID = "3b4b8383-09a1-4978-b4ba-349c8d3ad212"
# PROXYIP = "1.2.3.4"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "873c388d-afc4-4427-a947-8ed7305d9927"
